### ISSUE TITLE
Build Error - Intrinsic _mm256_loadu2_m128i Not Recognized

### ISSUE THREAD

**Issue by Anthony-Mai** [sleepybishop/nanorq#15]
I am unable to build this project. Tried it on several Linux machine and the build errors are the same. It seems it does not recognize the intrinsic _mm256_loadu2_m128i.

I am using gcc 9.4.0:
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Please advise how I can build this.

$ make
cc -O3 -g -std=c11 -Wall -Iinclude -Ideps/ -fPIC -march=native -funroll-loops -ftree-vectorize -Wno-unused -Wno-sequence-point -fstack-protector-all -DOBLAS_AVX2  -c -o deps/obl/oblas_lite.o deps/obl/oblas_lite.c
deps/obl/oblas_lite.c: In function ‘obl_axpy’:
deps/obl/oblas_lite.c:122:33: warning: implicit declaration of function ‘_mm256_loadu2_m128i’; did you mean ‘_mm256_loadu_si256’? [-Wimplicit-function-declaration]
  122 |         const __m256i urow_lo = _mm256_loadu2_m128i((__m128i *)u_lo, (__m128i *)u_lo);                                             \
      |                                 ^~~~~~~~~~~~~~~~~~~
deps/obl/oblas_lite.c:234:9: note: in expansion of macro ‘OBL_SHUF’
  234 |         OBL_SHUF(obl_axpy, a, b, OBL_SHUF_XOR);
      |         ^~~~~~~~
deps/obl/oblas_lite.c:122:33: error: incompatible types when initializing type ‘__m256i’ {aka ‘const __vector(4) long long int’} using type ‘int’
  122 |         const __m256i urow_lo = _mm256_loadu2_m128i((__m128i *)u_lo, (__m128i *)u_lo);                                             \
      |                                 ^~~~~~~~~~~~~~~~~~~
deps/obl/oblas_lite.c:234:9: note: in expansion of macro ‘OBL_SHUF’
  234 |         OBL_SHUF(obl_axpy, a, b, OBL_SHUF_XOR);
      |         ^~~~~~~~
deps/obl/oblas_lite.c:123:33: error: incompatible types when initializing type ‘__m256i’ {aka ‘const __vector(4) long long int’} using type ‘int’
  123 |         const __m256i urow_hi = _mm256_loadu2_m128i((__m128i *)u_hi, (__m128i *)u_hi);                                             \
      |                                 ^~~~~~~~~~~~~~~~~~~
deps/obl/oblas_lite.c:234:9: note: in expansion of macro ‘OBL_SHUF’
  234 |         OBL_SHUF(obl_axpy, a, b, OBL_SHUF_XOR);
      |         ^~~~~~~~
deps/obl/oblas_lite.c: In function ‘obl_scal’:
deps/obl/oblas_lite.c:122:33: error: incompatible types when initializing type ‘__m256i’ {aka ‘const __vector(4) long long int’} using type ‘int’
  122 |         const __m256i urow_lo = _mm256_loadu2_m128i((__m128i *)u_lo, (__m128i *)u_lo);                                             \
      |                                 ^~~~~~~~~~~~~~~~~~~
deps/obl/oblas_lite.c:240:5: note: in expansion of macro ‘OBL_SHUF’
  240 |     OBL_SHUF(obl_scal, a, a, OBL_NOOP);
      |     ^~~~~~~~
deps/obl/oblas_lite.c:123:33: error: incompatible types when initializing type ‘__m256i’ {aka ‘const __vector(4) long long int’} using type ‘int’
  123 |         const __m256i urow_hi = _mm256_loadu2_m128i((__m128i *)u_hi, (__m128i *)u_hi);                                             \
      |                                 ^~~~~~~~~~~~~~~~~~~
deps/obl/oblas_lite.c:240:5: note: in expansion of macro ‘OBL_SHUF’
  240 |     OBL_SHUF(obl_scal, a, a, OBL_NOOP);
      |     ^~~~~~~~
deps/obl/oblas_lite.c: In function ‘obl_axpy’:
deps/obl/oblas_lite.c:121:23: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
  121 |         const __m256i mask = _mm256_set1_epi8(0x0f);                                                                               \
      |                       ^~~~
deps/obl/oblas_lite.c:234:9: note: in expansion of macro ‘OBL_SHUF’
  234 |         OBL_SHUF(obl_axpy, a, b, OBL_SHUF_XOR);
      |         ^~~~~~~~
make: *** [<builtin>: deps/obl/oblas_lite.o] Error 1

**Comment by Intrepd** [comment]
It seems to build for me with -DOBLAS_AVX2 for me in 22.04

`gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)`

**Comment by sleepybishop** [comment]
The build defaults to AVX and I don't know what level of support for AVX gcc 9.4 has, but you can change the build to not require any special intrinsics by omitting

```c
 CPPFLAGS+="-DOBLAS_AVX -DOCTMAT_ALIGN=32"
```

in https://github.com/sleepybishop/nanorq/blob/stable/Makefile#L48.

**Comment by Anthony-Mai** [comment]
Thanks or your tip sleepybishop.

I commented out this in the Makefile:
-CPPFLAGS := -DOBLAS_AVX2
+#CPPFLAGS := -DOBLAS_AVX2

And I am able to build in GCC 9.4. Thanks again.
