### ISSUE TITLE
Make: missing gf2.h

### ISSUE THREAD

**Issue by Onion-Skins** [sleepybishop/nanorq#16]
Hi,

I am trying to compile the code but got this error when running make:
$ make
cc -O3 -g -std=c99 -Wall -I. -Iinclude -Ideps/oblas -march=native -funroll-loops -ftree-vectorize -fno-inline -fstack-protector-all -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64   -c -o encode.o encode.c
cc -O3 -g -std=c99 -Wall -I. -Iinclude -Ideps/oblas -march=native -funroll-loops -ftree-vectorize -fno-inline -fstack-protector-all -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64   -c -o lib/bitmask.o lib/bitmask.c
cc -O3 -g -std=c99 -Wall -I. -Iinclude -Ideps/oblas -march=native -funroll-loops -ftree-vectorize -fno-inline -fstack-protector-all -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64   -c -o lib/io.o lib/io.c
lib/io.c: In function ‘ioctx_mmap_file’:
lib/io.c:365:5: warning: ignoring return value of ‘ftruncate’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  365 |     ftruncate(fd, mapsize);
      |     ^~~~~~~~~~~~~~~~~~~~~~
lib/io.c: In function ‘mmapio_destroy’:
lib/io.c:321:5: warning: ignoring return value of ‘ftruncate’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  321 |     ftruncate(_io->fd, _io->filesize);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/io.c: In function ‘mmapio_seek’:
lib/io.c:211:7: warning: ignoring return value of ‘ftruncate’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  211 |       ftruncate(_io->fd, _io->filesize + _io->filesize);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc -O3 -g -std=c99 -Wall -I. -Iinclude -Ideps/oblas -march=native -funroll-loops -ftree-vectorize -fno-inline -fstack-protector-all -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64   -c -o lib/params.o lib/params.c
cc -O3 -g -std=c99 -Wall -I. -Iinclude -Ideps/oblas -march=native -funroll-loops -ftree-vectorize -fno-inline -fstack-protector-all -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64   -c -o lib/precode.o lib/precode.c
In file included from include/precode.h:8,
                 from lib/precode.c:1:
include/wrkmat.h:7:10: fatal error: gf2.h: No such file or directory
    7 | #include "gf2.h"
      |          ^~~~~~~
compilation terminated.
make: *** [<builtin>: lib/precode.o] Error 1

Would you please advise what I can do to resolve it?

Thanks a lot!

**Comment by Intrepd** [comment]
I think you first need to do:

```
git submodule init
git submodule update
```

...that will populate the deps/oblas/ directory with the required files

**Comment by Onion-Skins** [comment]
Sorry for missing this. It works now. Thanks a lot!

**Comment by Onion-Skins** [comment]
Sorry for missing this. It works now. Thanks a lot!
