### ISSUE TITLE
Using in data-carousel scenario

### ISSUE THREAD

**Issue by rafael2k** [sleepybishop/nanorq#22]
First of all - thanks for the amazing implementation!

In a data-carousel scenario (in which the data blocks are broadcast over and over again), how to optimally call nanorq_repair_block() when a sbn decode fails? For each new symbol received, I should call nanorq_decoder_add_symbol() and then try again nanorq_repair_block()?

Is there any sample implementation of a data-carousel use-case?

I'll publish the sample code I'm writing as soon as I get it right.

**Comment by sleepybishop** [comment]
Hi, thanks for your note.

I had at one point implemented behavior like this in another project via something like


```c
  int ret = nanorq_decoder_add_symbol(rq, data, tag, io);
  if (ret == NANORQ_SYM_ADDED) {
    added++;
    have_more_symbols = true;
  } else if (ret == NANORQ_SYM_DUP) {
    dups++
    have_more_symbols = false;
  }

  if (added >= nanorq_block_symbols(rq, b) && have_more_symbols) {
    nanorq_repair_block(rq, io, b);
  }
```

Hopefully this helps, I am not actively working on this code and never got around to cleaning up the api so I apologize for the clunkyness.

**Comment by rafael2k** [comment]
This sample is perfect. Thanks!
: )

**Comment by rafael2k** [comment]
I made a sample test of data carousel writing / reading from ring buffers in different processes (fountain is the source, dream is the sink):
https://github.com/rafael2k/c-playground/tree/main/raptorq
I works pretty neat. I implemented packet interleaving and "configuration frames" which I'll send periodically over the air through special more robust transmission frames. If you could take a look in:
https://github.com/rafael2k/c-playground/blob/main/raptorq/fountain.c
I would appreciate if you can see some obvious issue.

Nanorq is going over-the-air in HF at a 500km link.
: )

**Comment by rafael2k** [comment]
One more question: Is it OK to keep incrementing per block esi up to  ((1 << 24) - 1)) and then wrap around to 0 again in encode?

**Comment by sleepybishop** [comment]
Nice work! thank you for sharing.

To answer your question, no, per block you should not wrap around to 0 as you will create collisions with the original symbols. However the choices in rfc6330 around maximum number of blocks and repair symbols seemed arbitrary which is why I had hoped to create a simpler api around encoding/decoding a single block and applications could decide how to handle multiple blocks and the size of the repair queue.

**Comment by rafael2k** [comment]
Cool. The API is indeed very flexible! 
Another optimization I'm testing - if I want to reduce a bit the overhead of the tag size, could I use, lets say, 16 bits instead of 24 bits of esi in the tag and "free up" one byte (0x00ff0000) that I can use for other things. Of course I'll call nanorq_set_max_esi to (2^16 - 1). For small files use case, at least.

**Comment by rafael2k** [comment]
Forget about the latest question. Already implemented a more-or-less optimized tag header and initial parameters message. Your implementation is really well writen, easy to understand - thanks again!
: )
https://github.com/Rhizomatica/hermes-broadcast
