### ISSUE TITLE
nanorq_decode_block() sometimes return error data

### ISSUE THREAD

**Issue by xujiajundd** [sleepybishop/nanorq#3]
I try the lib and found that nanorq_decode_block() sometimes return error data.  when overhead = 0, the decoder should have a probability of 1/256 that the repair symbol is not enough and should return 0 for couldn't decode. but this lib always return data, and the data is not correct.

**Comment by sleepybishop** [comment]
thank your for reporting this bug, you're right, for the overhead = 0 case, there was an edge case not being handled and the nanorq_decode_block() was not returning an error.

this is fixed in https://github.com/sleepybishop/nanorq/commit/5144185406875f79b8f44ad6e081ce8d3448d414

**Comment by xujiajundd** [comment]
thanks!
