### ISSUE TITLE
can not interop with libraptorq

### ISSUE THREAD

**Issue by xujiajundd** [sleepybishop/nanorq#4]
I test the lib and found it is really faster than libraptorq, but unfortunately, the data encoded by libraptorq can not decoded by this lib and vice versa. Is it really comply with the RFC?

**Comment by sleepybishop** [comment]
the symbols generated should be the same, differences in encoder/decoder config would likely cause such issues.

**Comment by xujiajundd** [comment]
> the symbols generated should be the same, differences in encoder/decoder config would likely cause such issues.

I'm sure the oti_common and oti_scheme have no differences. Is there any other configs can be different? The branch I tested is sparse.

**Comment by sleepybishop** [comment]
a few months back i made some changes to try and make the encoder easier to configure and i hard coded the sub-block size (N parameter in oti_scheme) to 1. not sure if this is this cause of the issue, but i remember comparing against libraptorq 0.1.6 a while back and the symbols were the same. not sure what else could have changed since then.

also i would not recommend using sparse branch, it's not finished.

**Comment by xujiajundd** [comment]
> a few months back i made some changes to try and make the encoder easier to configure and i hard coded the sub-block size (N parameter in oti_scheme) to 1. not sure if this is this cause of the issue, but i remember comparing against libraptorq 0.1.6 a while back and the symbols were the same. not sure what else could have changed since then.
> 
> also i would not recommend using sparse branch, it's not finished.

my test is between libraptorq 0.1.10 and sparse branch of this lib on Mac OS and IOS. oti_scheme and oti_common is correct. when I encoded the data with libraptorq and decode with nanorq or vice versa, part of the decoded data will not correct if repair symbol is used.  
Mac os and IOS is big endian, and in libraptorq there is a configuration of endian. I'm not sure if this cause the issue?

**Comment by sleepybishop** [comment]
closing this, in theory they should work together but libraptorq interop is not really a goal of this project.

**Comment by Intrepd** [comment]
Sorry to comment on a closed issue -- we are seeing repair symbol differences from other implementations when the number of symbols in a block reaches 128 (we think).

In the case of 1280 symbol size and only 1 block, with the attached source, we normally see that the first repair symbol starts as:

`22a7c88e3bfb8136bf48052db25026702cd545b7f11b127b84ee5047d891458771694fd184d3f968...`

but nanorq generates:

`629993ff75a6a6652cdc6bdfcf461bebdf80ac945733fbc8dc2b7cafd8703cfb4acda8b7315adc50...`

[wnp-abridged-1280-128.txt](https://github.com/sleepybishop/nanorq/files/5840384/wnp-abridged-1280-128.txt)

**Comment by sleepybishop** [comment]
what implementations are you comparing against?

**Comment by Intrepd** [comment]
We've checked LucaFulchir/libRaptorQ, cberner/raptorq, and lorinder/TvRQ.  We are not that familiar with TvRQ, but at least in this case, it produces the same 0x22a7... repair symbol.

Thanks for the response.

**Comment by sleepybishop** [comment]
i'll have to double check the tuple generator and all the the data tables, maybe something is off.

**Comment by sleepybishop** [comment]
i went back in the version history and verified `22a7..` is the correct symbol, an optimization along the way broke it.

ill isolate the commit and restore the proper logic

**Comment by sleepybishop** [comment]
this is fixed on master with 234bd8e077cbfb972e7c57bf98a29a9e39d89a0c

also pushed master to stable

**Comment by Intrepd** [comment]
thank you for this--we're seeing nanorq generate identical repair symbols now.
