### ISSUE TITLE
Is is possible to upgrade lib oblas to the latest reversion for nanorq ?

### ISSUE THREAD

**Issue by netplus** [sleepybishop/nanorq#7]
Hello, 

Thanks for your good job on this projects, I notice that lib oblas has lots of updates, Is it possible to use the lastest reversion for nanorq ? 

Thanks.

**Comment by sleepybishop** [comment]
No, in fact my plan in to use a standalone oblas like i use nanors (https://github.com/sleepybishop/nanors/blob/master/oblas_lite.h) in nanorq as well, and leave the oblas project as a generic toolbox for finite field experiments.
