### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yuanshengyong** [sleepybishop/nanorq#8]
How should I use it

**Comment by viveksg** [comment]
A sample can be found in [encode.c](https://github.com/sleepybishop/nanorq/blob/stable/encode.c) and [decode.c](https://github.com/sleepybishop/nanorq/blob/stable/decode.c). You can start from checking main functions in both files.   
For encoding, you put your test data in a file and initialize [ioctx](https://github.com/sleepybishop/nanorq/blob/45ef20a8d6fe41a363890cd7c80efc78b551db00/io.h#L7) structure on that file.   Initialize the encoder instance based on filesize and payload size and alignment and then carry out the encoding.  
See dump_block and dump_esi functions for more details in the encode.c file.

Decoding is also a similar process. The encoded file is parsed for the common and scheme-specific parameters to initialize the decoder and then decoding is carried out in a block by block manner.    
Alternatively, you can put your test data in an array and initialize the  [ioctx](https://github.com/sleepybishop/nanorq/blob/45ef20a8d6fe41a363890cd7c80efc78b551db00/io.h#L7) using a pointer to that array, see [ioctx_from_mem](https://github.com/sleepybishop/nanorq/blob/45ef20a8d6fe41a363890cd7c80efc78b551db00/io.h#L20).  
Check [RFC 6330](https://datatracker.ietf.org/doc/html/rfc6330) for concepts.

**Comment by yuanshengyong** [comment]
How do I run

**Comment by viveksg** [comment]
clone the repo and update the oblas submodule.   
After that   
`make clean`    
`cd oblas`     
`make`    
`cd..`    
`make`  

This will also generate static-libs which you can include in your own test code.

**Comment by yuanshengyong** [comment]
Thank you for your answer

**Comment by sleepybishop** [comment]
Thank you @viveksg
