### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by viveksg** [sleepybishop/nanorq#9]
How to know the total number of repair symbols, when the encoder is initialized?

**Comment by sleepybishop** [comment]
Hello, apologies for the delayed response. I seem to no longer get notifications for my projects.

In any case, what you are looking for is the `K` value in https://github.com/sleepybishop/nanorq/blob/stable/nanorq.c#L33

also available via `nanorq_block_symbols(rq, sbn);`

**Comment by viveksg** [comment]
Thank you @sleepybishop
